### ISSUE TITLE
Performance vs. PolyLaneNet

### ISSUE THREAD

**Issue by voldemortX** [mo-vic/BezierLaneNet#1]
Hi! Great work here!
@mo-vic Myself and my colleagues are also thinking of using parametric curves in deep lane detection. I'm wondering what is the performance of using Bezier curve here (in terms of CULane's F1 score/TuSimple's Accuracy), and if it is better than PolyLaneNet (which use cubic polynomials).

**Comment by mo-vic** [comment]
Hi, @voldemortX, the model in this repo is just a baseline model! I use it to prove the feasibility of using bezier curve as lane representation, and I did not compare the performance of this model with PolyLaneNet. However, there is brief introduction of  [BezierLaneNet](https://mo-vic.github.io/2021/02/21/BezierLaneNet/) and also a [demo video](https://www.bilibili.com/video/BV1qV411i7jB?from=search&seid=6500970916972072217) of this baseline model on bilibili.
The main difference between BezierLaneNet and PolyLaneNet is curve representation, for fair comparison, you can get the code for PolyLaneNet, and modify some of the code to adapt to BezierLaneNet in the repo. 
For more information, feel free to contact me.

**Comment by voldemortX** [comment]
Thanks!
