### ISSUE TITLE
RuntimeError: Found dtype Float but expected Double

### ISSUE THREAD

**Issue by ayushmankumar7** [mo-vic/BezierLaneNet#3]
I ran train.py on my local machine, it ran flawlessly. 
For accelerating, I uploaded my Notebook and Dataset on Kaggle and I got this error. 
I know this is a bit weird but :) 

```
Traceback (most recent call last):
  File "../input/lane-detection-curve/BezierLaneNet/train.py", line 126, in <module>
    main()
  File "../input/lane-detection-curve/BezierLaneNet/train.py", line 108, in main
    train(model, train_loader, optimizer, criterion, args.beta, tr_writer, e, args.degree, use_gpu)
  File "/kaggle/input/lane-detection-curve/BezierLaneNet/utils/utils.py", line 153, in train
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Found dtype Float but expected Double

```

**Comment by mo-vic** [comment]
Since the code can run on your local machine, I guess the reason is that the version of PyTorch you used are different. 
But from the Traceback info, you could try to unify the datatype of both the network output and the target label before calling `loss.backward`.

**Comment by ayushmankumar7** [comment]
Okay. First,  I will try changing the Pytorch versions. If it works, then good. 
I tried converting the inputs to the model to double, but then I got the expected error that weights are in float(Cuda Float) but the inputs are in Cuda Double.

**Comment by mo-vic** [comment]
Well then, try to change the input back to float, and convert the target label to float as well, I guess the label is double type.

**Comment by ayushmankumar7** [comment]
Yo! Changing the Version helped! Thanks for the help!

**Comment by mo-vic** [comment]
😺
